services:
  app:
    image: ghcr.io/tomas-gen/web_polymem:latest
    pull_policy: always
    container_name: polymem
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_SITE_URL=https://www.polymemaislaciones.com.ar
